### ISSUE TITLE
It is unclear from the proposal how it helps with the memory management issues

### ISSUE THREAD

**Issue by smaug----** [shaseley/abort-signal-any#4]
https://github.com/shaseley/abort-signal-any/blob/main/README.md#userland-solutions hints that the proposal somehow helps with that example, but it isn't quite clear to me how. If the signal which follows other signals has an event listener for abort, the signal will need to stay alive as long as the other signals stay alive and aren't aborted.

**Comment by shaseley** [comment]
Right, these signals need to be kept alive whenever the abort from an ancestor signal can be observed. Assuming a signal has an ancestor that can still abort, this means the signal needs to be kept alive if:

1. The signal has an 'abort' event listener, as you mentioned
2. An abort algorithm has been added to the signal for an operation that has not yet completed, e.g. a fetch.

We can ensure signal lifetimes are sufficient by holding a strong reference from each source signal to each derived signal, but then the lifetime of the derived signal is tied to that of the source, which can be leaky (lifetime is tied to source — bad if combining with top-level signals).

But, we don't *always* need a strong reference:

- **Nothing can observe**: If both (1) and (2) above are false, no strong reference is needed
- **Nothing to observe**: If all abort sources are "settled", meaning we know they won't abort (e.g. a signal is associated with an `AbortController` that has been GCed)

I would argue that the UA is in a much better position to do this management (figuring out when a strong ref is needed). You can get close in userland with finalization registries and overriding `[add|remove]EventListener()`, but I think (2) requires monkey patching anything that takes a signal[^1].

[^1]: At least in Chromium, not all objects that add algorithms hold a reference to the signal, and some specs just say to directly add an algorithm to the signal passed in the options.

I've been putting together a prototype in Chromium. Most of this was straightforward, but I just realized (2) was a problem (we either don't hold a reference to the signal or don't remove algorithms on completion), so I'm working on fixing that.

Related docs on memory management:
 - [Lifetime of AbortSignals & AbortAlgorithm Lifetime](https://docs.google.com/document/d/1UMZrd5-RztLLUZ2g4vf4Nk7MBTnpfdihNi1Xh5qrND8/edit?usp=sharing&resourcekey=0-Xd_3IULrml81fZ7CGrltYw)
 - [`AbortSignal.any()` Memory Management](https://docs.google.com/document/d/1LvmsBLV85p-PhSGvTH-YwgD6onuhh1VXLg8jPlH32H4/edit?usp=sharing)

**Comment by shaseley** [comment]
Quick follow-up, I brain-dumped a bit more detail and thoughts on signal memory management [here](https://github.com/shaseley/abort-signal-any/blob/main/signal-memory-management.md). Feedback welcome :). Assuming one wants to optimize this, I think this approach works and the UA is in a good position to do it. Protoyping it now to prove that out and to see if I uncover anything else.

**Comment by jimmywarting** [comment]
how could this be solved using user-land polyfill that dependend upon WeakRefs and Finalizers? 
don't really care about really old env like IE anymore

I guess it would go something like:

```js
const registry = new FinalizationRegistry(heldValue => {
  // clean up
})

AbortSignal.any ??= function (signals) {
  if (!Array.isArray(signals)) {
    throw new TypeError('Expected an array of signals')
  }

  const ctrl = new AbortController()
  
  if (signals.length === 0) {
    return ctrl.signal
  }

  // Check if any signal is already aborted
  for (const signal of signals) {
    if (signal.aborted) {
      ctrl.abort(signal.reason)
      return ctrl.signal
    }
  }

  function abort() {
    // weakRef.deref()?....

    // Remove the abort listener from all other signals
  }

  const weakRef = new WeakRef(...)

  for (const signal of signals) {
    signal.addEventListener('abort', abort, { once: true })
  }
  
  const heldValue = { ... }
  registry.register(ctrl.signal, heldValue)

  return ctrl.signal
}
```
a bit unfinished

**Comment by shaseley** [comment]
I started working on a polyfill for when I was designing the API, but found you can only handle some of the cases. The challenge is ensuring dependent signals stay alive while they have (1) internal abort algorithms or (2) abort event listeners, and I don't think that's possible without monkey patching a bunch of stuff and trying to track those things in userland.

For (1), the problem is things like:

```js
await signalTakingAPI({signal: AbortSignal.any([otherSignal]));
```

The temporary passed to the API needs to be kept alive somewhere while the operation is still in progress. But you generally can't rely on the implementation to hold onto the signal,  e.g. Blink's web locks implementation doesn't hold a strong reference to the signal, it just adds an abort algorithm to the signal it takes (note: for other signals, the controller or timeout keeps the signal alive). This is likely to vary by API and implementation, and to have a complete and reliable implementation, you'd probably need to monkey patch the APIs, tracking outstanding operations associated with the signal (holding a strong reference while in progress).

(2) is basically the userland equivalent (1), where `signalTakingAPI` is a userland function that adds an abort event listener to the incoming signal without holding a reference to it. You'd need to hold a strong reference to it as long as it has abort event listeners, which I think would mean you'd need to monkey patch `AbortSignal.prototype.[add|remove|EventListener()` and `onabort`.
